import { useMemo } from 'react'; import { Pressable, StyleSheet, View } from 'react-native'; import { router } from 'expo-router'; import { doc } from 'firebase/firestore'; import { Ionicons } from '@expo/vector-icons';
import { Screen } from '@/components/ui/Screen'; import { AppHeader } from '@/components/navigation/AppHeader'; import { Text } from '@/components/ui/Text'; import { Card } from '@/components/ui/Card'; import { EmptyState, LoadingState } from '@/components/ui/StateView';
import { useAuth } from '@/providers/AuthProvider'; import { useTheme } from '@/hooks/useTheme'; import { useOrders } from '@/hooks/useOrders'; import { useRealtimeDocument } from '@/hooks/useRealtimeDocument'; import { db } from '@/lib/firebase'; import { formatNaira, formatLitres } from '@/lib/format'; import { colors, radii, spacing } from '@/theme/tokens';
import type { Order } from '@/types/domain';
type MarketSettings = { currentPricePerLitre: number; previousPricePerLitre: number; updatedAt?: unknown };
const actions = [{ title: 'Quick order', icon: 'flash', path: '/order/location' }, { title: 'Emergency', icon: 'alert-circle', path: '/order/location?emergency=true' }, { title: 'Schedule', icon: 'calendar', path: '/order/location?scheduled=true' }] as const;
export function CustomerDashboard() {
  const { profile } = useAuth(); const theme = useTheme(); const { data: orders, loading } = useOrders(5); const settingsRef = useMemo(() => doc(db, 'settings', 'market'), []); const { data: market } = useRealtimeDocument<MarketSettings>(settingsRef); const displayMarket = market ?? { currentPricePerLitre: 1250, previousPricePerLitre: 1200 }; const trend = displayMarket.currentPricePerLitre - displayMarket.previousPricePerLitre;
  return <Screen header={<AppHeader />}><View style={styles.greeting}><View><Text color={theme.colors.muted}>Good to see you</Text><Text variant="h1">{profile?.displayName?.split(' ')[0] || 'Customer'}</Text></View><View style={styles.verified}><Ionicons name="shield-checkmark" size={15} color={colors.success} /><Text variant="caption" color={colors.success}>Secure account</Text></View></View><Card style={styles.priceCard}><View><Text variant="caption" color="#CBD5E1">MARKET PRICE</Text><View style={styles.price}><Text color="white" style={styles.priceValue}>{formatNaira(displayMarket.currentPricePerLitre)}</Text><Text color="#CBD5E1"> / litre</Text></View><Text variant="caption" color={trend <= 0 ? '#6EE7B7' : '#FCD34D'}>{trend === 0 ? 'No price movement' : `${trend > 0 ? '↑' : '↓'} ${formatNaira(Math.abs(trend))} since last update`}</Text></View><Ionicons name="water" size={74} color="#FFFFFF14" /></Card><View style={styles.actionGrid}>{actions.map((action) => <Pressable key={action.title} onPress={() => router.push(action.path as never)} style={[styles.action, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><View style={styles.actionIcon}><Ionicons name={action.icon} size={22} color={colors.primary} /></View><Text variant="label">{action.title}</Text></Pressable>)}</View><View style={styles.sectionTitle}><Text variant="h2">Recent orders</Text><Pressable onPress={() => router.push('/(app)/(tabs)/orders')}><Text variant="label" color={colors.primary}>See all</Text></Pressable></View>{loading ? <LoadingState label="Loading orders…" /> : orders.length === 0 ? <EmptyState icon="receipt-outline" title="No orders yet" message="Your real orders will appear here after checkout." actionTitle="Order diesel" onAction={() => router.push('/order/location')} /> : <View style={styles.list}>{orders.map((order) => <OrderRow key={order.id} order={order} />)}</View>}<View style={styles.sectionTitle}><Text variant="h2">Saved locations</Text><Pressable onPress={() => router.push('/addresses')}><Text variant="label" color={colors.primary}>Manage</Text></Pressable></View><Card><Text color={theme.colors.muted}>Add a saved location during checkout or from the Manage screen.</Text></Card></Screen>;
}
function OrderRow({ order }: { order: Order }) { const theme = useTheme(); return <Pressable onPress={() => router.push(`/orders/${order.id}` as never)}><Card style={styles.order}><View style={styles.orderIcon}><Ionicons name="water" color={colors.primary} size={20} /></View><View style={styles.orderCopy}><Text variant="label">{order.orderNumber}</Text><Text variant="caption" color={theme.colors.muted}>{formatLitres(order.quantityLitres)} • {order.deliveryAddress.label}</Text></View><View style={styles.orderRight}><Text variant="label">{formatNaira(order.money.total)}</Text><Text variant="caption" color={colors.accent}>{order.status.replaceAll('_', ' ')}</Text></View></Card></Pressable>; }
const styles = StyleSheet.create({ greeting: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.xl }, verified: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#ECFDF5', borderRadius: radii.full, paddingHorizontal: 10, paddingVertical: 6 }, priceCard: { minHeight: 168, backgroundColor: colors.secondary, borderColor: colors.secondary, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', overflow: 'hidden', padding: spacing.xl }, price: { flexDirection: 'row', alignItems: 'baseline', marginVertical: spacing.sm }, priceValue: { fontSize: 31, lineHeight: 38, fontWeight: '800' }, actionGrid: { flexDirection: 'row', gap: spacing.md, marginVertical: spacing.xl }, action: { flex: 1, minHeight: 94, borderWidth: 1, borderRadius: radii.lg, padding: spacing.md, gap: spacing.sm, justifyContent: 'center' }, actionIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#FFF3E5', alignItems: 'center', justifyContent: 'center' }, sectionTitle: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.xl, marginBottom: spacing.md }, list: { gap: spacing.sm }, order: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, orderIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#FFF3E5', alignItems: 'center', justifyContent: 'center' }, orderCopy: { flex: 1, gap: 3 }, orderRight: { alignItems: 'flex-end', gap: 3 } });
