import { useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { Controller, useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Screen } from '@/components/ui/Screen'; import { Brand } from '@/components/ui/Brand'; import { Text } from '@/components/ui/Text'; import { Input } from '@/components/ui/Input'; import { Button } from '@/components/ui/Button'; import { Card } from '@/components/ui/Card';
import { useAuth } from '@/providers/AuthProvider'; import { colors, radii, spacing } from '@/theme/tokens'; import type { UserRole } from '@/types/domain';

const schema = z.object({ name: z.string().trim().min(2, 'Enter your full name'), email: z.email(), phoneNumber: z.string().trim().min(10, 'Enter a valid phone number').optional().or(z.literal('')), password: z.string().min(8).regex(/[A-Z]/, 'Add one uppercase letter').regex(/[0-9]/, 'Add one number') });
type Values = z.infer<typeof schema>; const roles: { value: Extract<UserRole, 'customer' | 'supplier' | 'driver'>; label: string }[] = [{ value: 'customer', label: 'Customer' }, { value: 'supplier', label: 'Supplier' }, { value: 'driver', label: 'Driver' }];
export default function RegisterScreen() {
  const { register } = useAuth(); const [role, setRole] = useState<(typeof roles)[number]['value']>('customer'); const [error, setError] = useState('');
  const { control, handleSubmit, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { name: '', email: '', phoneNumber: '', password: '' } });
  const submit = handleSubmit(async (values) => { try { setError(''); await register({ ...values, phoneNumber: values.phoneNumber || undefined, role }); router.replace('/'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Account creation failed.'); } });
  return <Screen contentStyle={styles.content}><View style={styles.top}><Brand /><Pressable onPress={() => router.back()}><Text color={colors.primary}>Back</Text></Pressable></View><Card style={styles.card}><View style={styles.title}><Text variant="h1">Create your account</Text><Text color="#64748B">Choose how you’ll use DieselUp. Operational accounts are verified before activation.</Text></View><View style={styles.roles}>{roles.map((item) => <Pressable key={item.value} onPress={() => setRole(item.value)} style={[styles.role, { borderColor: role === item.value ? colors.primary : '#E2E8F0', backgroundColor: role === item.value ? '#FFF7ED' : 'transparent' }]}><Text variant="label" color={role === item.value ? colors.primary : undefined}>{item.label}</Text></Pressable>)}</View>{error ? <Text color={colors.danger}>{error}</Text> : null}<Controller name="name" control={control} render={({ field }) => <Input label={role === 'supplier' ? 'Contact name' : 'Full name'} icon="person-outline" value={field.value} onChangeText={field.onChange} error={errors.name?.message} />} /><Controller name="email" control={control} render={({ field }) => <Input label="Email address" icon="mail-outline" autoCapitalize="none" keyboardType="email-address" value={field.value} onChangeText={field.onChange} error={errors.email?.message} />} /><Controller name="phoneNumber" control={control} render={({ field }) => <Input label="Phone number" icon="call-outline" keyboardType="phone-pad" value={field.value} onChangeText={field.onChange} error={errors.phoneNumber?.message} />} /><Controller name="password" control={control} render={({ field }) => <Input label="Password" icon="lock-closed-outline" secureTextEntry value={field.value} onChangeText={field.onChange} error={errors.password?.message} />} /><Button title="Create account" loading={isSubmitting} onPress={submit} /><View style={styles.signin}><Text color="#64748B">Already registered?</Text><Pressable onPress={() => router.replace('/(auth)/sign-in')}><Text variant="label" color={colors.primary}>Sign in</Text></Pressable></View></Card></Screen>;
}
const styles = StyleSheet.create({ content: { flexGrow: 1, justifyContent: 'center', gap: spacing.xl }, top: { width: '100%', maxWidth: 560, alignSelf: 'center', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, card: { width: '100%', maxWidth: 560, alignSelf: 'center', gap: spacing.lg, padding: spacing.xl }, title: { gap: spacing.sm }, roles: { flexDirection: 'row', gap: spacing.sm }, role: { flex: 1, minHeight: 44, borderWidth: 1, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center' }, signin: { flexDirection: 'row', justifyContent: 'center', gap: spacing.sm } });
