import { StyleSheet, View, useWindowDimensions } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '@/components/ui/Screen';
import { Brand } from '@/components/ui/Brand';
import { Text } from '@/components/ui/Text';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { colors, radii, spacing } from '@/theme/tokens';

const assurances = [['shield-checkmark', 'Verified supply network'], ['navigate', 'Live delivery tracking'], ['card', 'Secure payments']] as const;

export default function WelcomeScreen() {
  const { width } = useWindowDimensions(); const wide = width >= 900;
  return <Screen contentStyle={[styles.content, wide && styles.wide]}><View style={[styles.copy, wide && styles.copyWide]}><Brand /><View style={styles.heroText}><Text variant="hero">Diesel delivered.{`\n`}Operations uninterrupted.</Text><Text color="#64748B" style={styles.lead}>Order from verified suppliers, pay securely, and follow every litre from depot to destination.</Text></View><View style={styles.assurances}>{assurances.map(([icon, label]) => <View key={label} style={styles.assurance}><View style={styles.assuranceIcon}><Ionicons name={icon} size={17} color={colors.primary} /></View><Text variant="label">{label}</Text></View>)}</View><View style={styles.actions}><Button title="Create account" icon="arrow-forward" onPress={() => router.push('/(auth)/register')} /><Button title="Sign in" variant="outline" onPress={() => router.push('/(auth)/sign-in')} /></View><Text variant="caption" color="#64748B">By continuing, you agree to DieselUp’s Terms and Privacy Policy.</Text></View>{wide && <LinearGradient colors={['#111827', '#0F172A', '#1E293B']} style={styles.visual}><View style={styles.glow} /><Text color="#FDBA74" variant="label">LIVE OPERATIONS</Text><Text color="white" style={styles.visualNumber}>One order.{`\n`}Every moving part.</Text><Card style={styles.routeCard}><View style={styles.routeTop}><View><Text variant="caption" color="#64748B">ACTIVE DELIVERY</Text><Text variant="h3">En route</Text></View><View style={styles.pill}><View style={styles.dot} /><Text variant="caption" color={colors.success}>Live</Text></View></View><View style={styles.route}><View style={styles.pin}><Ionicons name="business" color="white" size={15} /></View><View style={styles.line} /><View style={[styles.pin, { backgroundColor: colors.primary }]}><Ionicons name="location" color="white" size={15} /></View></View><Text variant="caption" color="#64748B">The live map activates when a real driver is assigned.</Text></Card></LinearGradient>}</Screen>;
}
const styles = StyleSheet.create({ content: { flexGrow: 1, padding: 0 }, wide: { flexDirection: 'row', maxWidth: 1440 }, copy: { flex: 1, justifyContent: 'center', padding: spacing.xl, gap: spacing['2xl'] }, copyWide: { padding: 72 }, heroText: { gap: spacing.md, maxWidth: 580 }, lead: { fontSize: 17, lineHeight: 26 }, assurances: { gap: spacing.md }, assurance: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, assuranceIcon: { width: 34, height: 34, borderRadius: 12, backgroundColor: '#FFF3E5', alignItems: 'center', justifyContent: 'center' }, actions: { gap: spacing.md, maxWidth: 420 }, visual: { flex: 1, margin: spacing.lg, borderRadius: 28, padding: 64, justifyContent: 'center', overflow: 'hidden', gap: spacing.lg }, glow: { position: 'absolute', top: -100, right: -80, width: 340, height: 340, borderRadius: 170, backgroundColor: '#FF8A0033' }, visualNumber: { fontSize: 42, lineHeight: 49, fontWeight: '800' }, routeCard: { marginTop: spacing.xl, maxWidth: 440, gap: spacing.xl }, routeTop: { flexDirection: 'row', justifyContent: 'space-between' }, pill: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#ECFDF5', borderRadius: radii.full, paddingHorizontal: 10, paddingVertical: 5 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.success }, route: { flexDirection: 'row', alignItems: 'center' }, pin: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.secondary, alignItems: 'center', justifyContent: 'center' }, line: { height: 3, flex: 1, backgroundColor: '#FED7AA' } });
